### ISSUE TITLE
Book a venue

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#1]
Dreamplex 2 Auditorium - https://dreamplex.co/location/auditorium-dreamplex-195_684.html

**Comment by plutov** [comment]
Today I visited Auditorium and we have discount 10% (as I am working in Dreamplex)

**Comment by plutov** [comment]
Check `272 võ thị sáu` addr

**Comment by tieubao** [comment]
Confirmed from CoderSchool that we can use their office for Workshop, and confirmed with Dreamplex to book Auditorium for conference.
