### ISSUE TITLE
Find sponsors

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#10]
Potential sponsors:

 - JetBrains
 - Grab
 - Trusting Social
 - GoViet / GoJek
 - Lazada
 - Chotot.vn

**Comment by plutov** [comment]
Talking to JetBrains, they are happy to become a Platinum sponsors, still in discussion.

**Comment by plutov** [comment]
Sent email to Cassandra from Google.

**Comment by RuniVN** [comment]
Talked to Axon, a 30-40 mil package is acceptable. Still in discussion.

**Comment by plutov** [comment]
Let's list all sponsors in this doc and do not share it yet with the audience. https://docs.google.com/spreadsheets/d/1tQFKfOUov18-GKOsEjpzcMmyuT1gsExelnxh28f8lqE
