### ISSUE TITLE
Find speakers

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#11]
https://www.papercall.io/gopherconvn2018

**Comment by plutov** [comment]
Talking to William Kennedy, he is asking to cover T&E costs.

**Comment by tieubao** [comment]
I'm arranging. There are some companies that want to help

**Comment by RuniVN** [comment]
We can contact with local + Asia companies to ask for speakers.
Target:
- Gojek
- SEA
- Grab
- LINE

**Comment by RuniVN** [comment]
T&E costs seems is quite big amount of money. Let's consider inviting William Kennedy. We can invite somebody whose cost can be covered by his company.

**Comment by tieubao** [comment]
The conference day is full of talks. We should confirm with them and close this issue
