### ISSUE TITLE
Design and prepare standees

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#14]
Amount: 2.

1 in the entrance, 2 inside

**Comment by plutov** [comment]
Auditorium Dreamplex will provide 1 standee for free

**Comment by tieubao** [comment]
Size of standee: 80 x 180

<img width="272" alt="screen shot 2018-11-07 at 2 36 38 am" src="https://user-images.githubusercontent.com/1749624/48085717-05e7f880-e236-11e8-9da5-6e493dfb84db.png">

@RuniVN Need to confirm list of sponsors before printing

https://github.com/golang-vietnam/gophercon-2018/issues/10
