### ISSUE TITLE
Make Gophercon.vn specific logo

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#5]
with a conus hat

**Comment by tieubao** [comment]
good idea @plutov

**Comment by plutov** [comment]
Tanya Shumskaya is looking for a designer. We will use this logo for t-shirt, stickers, website, etc.

**Comment by plutov** [comment]
TODO: check with designer in Go team.

**Comment by astoliarov** [comment]
@plutov I have one free designer who can try to help you with Go mascot styling

**Comment by plutov** [comment]
Hi @astoliarov that's amazing! Let us think about the styling and I'll let you know.

**Comment by tieubao** [comment]
that would be very helpful @astoliarov

**Comment by astoliarov** [comment]
Hi. Are you still interesting in gopher logo? My comrade-designer felt such a great motivation when saw a gopher, so she created a prototype of logo
![logo_gofer](https://user-images.githubusercontent.com/10893844/45239557-530b2500-b2ee-11e8-89c5-f1f0e0794fb0.png)

**Comment by tieubao** [comment]
![screen shot 2018-09-24 at 9 25 55 pm](https://user-images.githubusercontent.com/1749624/45957971-73521800-c040-11e8-8dba-28d38582709e.png)

Another artwork provided by @dwarvesf

**Comment by plutov** [comment]
This is really awesome!

**Comment by tieubao** [comment]
I think it's good to close the issue
