### ISSUE TITLE
Print stickers: Go, Sponsors, etc.

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#7]

**Comment by tieubao** [comment]
4 x 500 for each

sample:

![sticker2](https://user-images.githubusercontent.com/1749624/48085862-6840f900-e236-11e8-8ee1-9e9b80760c89.png)

![sticker1](https://user-images.githubusercontent.com/1749624/48085876-7131ca80-e236-11e8-8605-e2b19d83d71f.png)
