### ISSUE TITLE
Prepare N badges for attendees

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon#8]
2-side badge.

Front side: Name and Company
Back side: Conference Schedule

**Comment by tieubao** [comment]
Add role & position

**Comment by tieubao** [comment]
<img width="774" alt="screen shot 2018-12-05 at 10 52 27 am" src="https://user-images.githubusercontent.com/1749624/49489040-e1565f00-f87b-11e8-985d-7ccadab9f199.png">

Designed by @dwarvesf
